name: Publish API documentation (snapshot)
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write

jobs:
  publish-doc-snapshot:
    uses: jeanpierrefortune/keyple.keyple-actions/.github/workflows/reusable-publish-doxygen.yml@main
    secrets: inherit