name: Publish API documentation (release)
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (ex: 1.0.0)'
        required: true

permissions:
  checks: write

jobs:
  publish-doc-release:
    uses: jeanpierrefortune/keyple.keyple-actions/.github/workflows/reusable-publish-doxygen.yml@main
    with:
      version: ${{ github.event.inputs.version || github.ref_name }}
    secrets: inherit